#!/bin/sh

# Example:
# $ printf "1 a A\n1 b B\n2 c C\n3 d D\n" | ./bred 'sed -e "s/^.*$/& {} {}/"'
# d D 3 3
# c C 2 2
# a A 1 1
# b B 1 1

cmd=${1:?"reducer command line must be provided"}
key_index=${2:-1}

key_index=$key_index \
cmd=$1 awk '{
    prev="";
    line="\0";
    for (i=1; i <=NF; i++) {
        if (i!=ENVIRON["key_index"]) {
            if (line == "\0") {
                line=$i;
            } else {
                line=sprintf("%s%s%s",line,FS,$i);
            }
        }
    }
    key = $ENVIRON["key_index"];
    cmd=ENVIRON["cmd"] " | sed -e \"s/^.*$/" key FS "&/\"";
    gsub("{}", key, cmd);
    print line | cmd;
    if (prev != "" && prev != cmd) { close(prev); }
    prev=cmd;
}
END {
    close(prev);
}'
